"""Composer — formats ranked articles into newsletters and Xiaohongshu-ready text."""

import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

XHS_MAX_CHARS = 950  # Slightly under 1000 to be safe


def compose_all(
    results: dict[str, list[dict]],
    output_dir: str,
    week_start: str,
) -> dict[str, str]:
    """Generate 3 newsletters + xhs_text + comparison for all algorithms.

    Each article in results should have:
      id, title, url, source, score, summary_cn, image_path

    Returns {alg_name: {"newsletter": path, "xhs_text": path}}
    """
    base = Path(output_dir)
    algo_names = {
        "hotness": "热度优先",
        "impact": "影响力优先",
        "freshness": "新鲜度优先",
    }

    outputs = {}
    for alg, articles in results.items():
        alg_dir = base / alg
        alg_dir.mkdir(parents=True, exist_ok=True)

        newsletter_path = alg_dir / "newsletter.md"
        xhs_path = alg_dir / "xhs_text.md"

        _write_newsletter(newsletter_path, articles, alg, algo_names.get(alg, alg), week_start)
        _write_xhs_text(xhs_path, articles, algo_names.get(alg, alg), week_start)

        outputs[alg] = {
            "newsletter": str(newsletter_path),
            "xhs_text": str(xhs_path),
        }

    # Comparison overview
    _write_comparison(base / "comparison.md", results, algo_names, week_start)

    logger.info(f"Composed 3 newsletters to {output_dir}")
    return outputs


def _write_newsletter(path: Path, articles: list[dict], alg_key: str, alg_label: str, week: str):
    lines = [
        f"# AI Weekly Top 10 — {alg_label}",
        f"**{week}** | 算法: {alg_key} | 更新时间: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
    ]

    for i, art in enumerate(articles, 1):
        title = art.get("title", "Untitled")
        url = art.get("url", "")
        source = art.get("source", "")
        score = art.get("score", 0)
        summary = art.get("summary_cn", "（无摘要）")
        image = art.get("image_path", "")

        lines.append(f"## {i}. {title}")
        lines.append(f"**来源**: {source} | **评分**: {score:.4f}")
        lines.append("")
        lines.append(summary)
        lines.append("")
        if image:
            lines.append(f"![{title}]({image})")
            lines.append("")
        if url:
            lines.append(f"> 🔗 [原文链接]({url})")
        lines.append("---")
        lines.append("")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by AI Weekly Bot — {datetime.now().strftime('%Y-%m-%d')}*")

    path.write_text("\n".join(lines), encoding="utf-8")


def _write_xhs_text(path: Path, articles: list[dict], alg_label: str, week: str):
    lines = [
        f"🔥 AI Weekly Top 10 | {week}",
        f"({alg_label} · 每周精选)",
        "",
    ]

    total = 0
    for i, art in enumerate(articles, 1):
        title = art.get("title", "")
        summary = art.get("summary_cn", "")

        # Truncate summary per item to fit overall limit
        max_summary = 80
        short_summary = summary[:max_summary] + "..." if len(summary) > max_summary else summary

        line = f"{i}. {title[:40]}\n{short_summary}\n"
        total += len(line)
        if total > XHS_MAX_CHARS:
            break
        lines.append(line)

    lines.append("")
    lines.append("🔗 原文链接见评论区置顶")
    lines.append("")
    lines.append("#AI #人工智能 #科技资讯 #每周AI #AI前沿")
    lines.append("")
    # Only mention images if any were generated
    has_images = any(art.get("image_path") for art in articles)
    if has_images:
        lines.append("📸 配图已生成，请配合图片以图文笔记形式发布")
    else:
        lines.append("📸 配图未生成，可以纯文字发布或用 emoji 装饰")

    path.write_text("\n".join(lines), encoding="utf-8")


def _write_comparison(
    path: Path,
    results: dict[str, list[dict]],
    algo_names: dict[str, str],
    week: str,
):
    lines = [
        f"# AI Weekly Top 10 — 三版对比",
        f"**{week}** | 生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "快速预览三份榜单，选出你要发布的那一版。",
        "",
        "---",
        "",
    ]

    # Side-by-side title list
    for alg, articles in results.items():
        label = algo_names.get(alg, alg)
        lines.append(f"## {label} (`{alg}`)")
        for i, art in enumerate(articles[:10], 1):
            title = art.get("title", "")
            score = art.get("score", 0)
            lines.append(f"  {i}. {title[:70]} ({score:.4f})")
        lines.append("")

    # Overlap analysis
    lines.append("---")
    lines.append("## 重叠分析")
    lines.append("")

    alg_keys = list(results.keys())
    all_titles: dict[str, set[str]] = {}
    for alg in alg_keys:
        all_titles[alg] = {art.get("title", "") for art in results.get(alg, [])}

    for i, a1 in enumerate(alg_keys):
        for a2 in alg_keys[i + 1 :]:
            overlap = all_titles[a1] & all_titles[a2]
            lines.append(f"- **{algo_names[a1]}** ∩ **{algo_names[a2]}**: {len(overlap)} 条共同")
            for t in overlap:
                lines.append(f"  - 🏷️ {t[:60]}")

    # Exclusive items
    lines.append("")
    for alg in alg_keys:
        others = set()
        for a2 in alg_keys:
            if a2 != alg:
                others |= all_titles[a2]
        exclusive = all_titles[alg] - others
        if exclusive:
            lines.append(f"**{algo_names[alg]} 独占**: {len(exclusive)} 条")
            for t in exclusive:
                lines.append(f"  - ✨ {t[:60]}")

    lines.append("")
    lines.append("---")
    lines.append("*Pick your favorite edition, then copy the xhs_text.md and images to publish.*")

    path.write_text("\n".join(lines), encoding="utf-8")
